### ISSUE TITLE
Issue while creating Installer

### ISSUE THREAD

**Issue by ashokbugude** [artoolkit/arunity5#60]
Hi,

I am using Unity in windows 7 

I am trying to generate installer for the project .Followed the steps in 
http://artoolkit.org/documentation/doku.php?id=1_Getting_Started:general_deploy_application

But I am getting the attached error. Could you pls help 

Attaching the following
1. Error Message
2. Inno Setup Script in txt file
[ARInnoSetup.txt](https://github.com/artoolkit/arunity5/files/173263/ARInnoSetup.txt)

Script

![error](https://cloud.githubusercontent.com/assets/10016848/13767680/3a7aaea0-ea93-11e5-8529-4ae51d111623.JPG)

**Comment by Seelhoff-DAQRI** [comment]
You do not have a [Components] section, so there is no "runtime" component at all.  You either need to add this section, with a "runtime" entry, or else remove the offending 'Components' parameter.  (Note: The first solution would be better, unless you are sure that the 'runtime' component is not required.)

**Comment by philip-lamb** [comment]
@Seelhoff-DAQRI Nice catch. I've updated the docs.

**Comment by ashokbugude** [comment]
Hi , Thanks for your response

I have removed component parameter from the script .Able to create setup file.
But getting the attached error while running the setup file.Pls help

Attaching
1. Modified script
2. Error screenshot

[ARInnoSetupScript.txt](https://github.com/artoolkit/arunity5/files/175309/ARInnoSetupScript.txt)



![setuperror](https://cloud.githubusercontent.com/assets/10016848/13802771/0a8e22d0-eb65-11e5-89a8-0cffafe41121.JPG)

**Comment by philip-lamb** [comment]
Please read the updated docs. Command-line options have changed for vc_redist.

**Comment by ashokbugude** [comment]
Hi

I have used the updated run command "Filename: {app}\vcredist_x86.exe; Parameters: "/install /quiet /norestart"; StatusMsg: Installing Visual Studio 2013 RunTime..."  but still getting the same error. When I install the file 'vcredist_x86.exe'. I do not get any error.
![setuperror](https://cloud.githubusercontent.com/assets/10016848/13808497/52ed110e-eb8c-11e5-88af-7ce14f03f82e.JPG)

**Comment by philip-lamb** [comment]
Why are you installing the Microsoft Visual Studio 2005 redistributable?

This as not an ARToolKit issue.

**Comment by ashokbugude** [comment]
Can I know which version of the file to be installed?should it the latest
one ?

**Comment by ashokbugude** [comment]
Hi I have used 2013 version . Its working fine . Thanks a lot


I have a doubt , could you pls help

I have unity installed in windows 7 , created the setup file , included all dll files, works fine

When I install the same in windows 8 , where **unity is not installed** .I get **ARWrapper.dll not found** when i run the application. I have installed vcredist_64.exe in windows 8 . Since Unity is not installed, I have placed the dll files in c:/windows/system32 location where cmd.exe is present. But the errors still persist
Pls help to resolve the issue . Do I need to create it as new Issue
